on: [push]
name: Azure ARM
permissions:
  id-token: write
  contents: read
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:

      # Checkout code
    - uses: actions/checkout@main

      # Log into Azure
    - uses: azure/login@v1
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        
    - name: Install Bicep  
      run: |  
        curl -Lo bicep https://github.com/Azure/bicep/releases/latest/download/bicep-linux-x64  
        chmod +x ./bicep  
        sudo mv ./bicep /usr/local/bin/bicep  
        bicep --help  
  
    - name: Validate Bicep file  
      run: |  
        bicep build ./infra/main.bicep  
  
    - name: Deploy Bicep file  
      run: |  
        az deployment sub create --location eastus --template-file ./infra/main.bicep  --parameters 'authClientId=e71e0f15-47d7-4d07-9940-c23adfa9bcde authClientSecret=Npy8Q~Yqf9yYe5Ny58C2R6mRO7zz660EV_4ezb_d environmentName=dev location=eastus'
     
